### ISSUE TITLE
Session and Speaker Feedbak

### ISSUE THREAD

**Issue by MocGio** [Axelera/SUMilanApp#23]
Potremmo far apparire sulla Web App un questionario a fine evento per raccogliere un feedback su ogni singolo relatore,(con un voto da es 0 a 5), o sulla sessione in generale, potremmo anche lasciare uno spazio per raccogliere  suggerimenti, idee di miglioramenti sulla web app.

**Comment by ilbertt** [comment]
Tracking in #21, closing this.
